# Generated by Django 4.2.6 on 2023-11-22 00:42

import aplicacion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[aplicacion.models.validate_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField(default=1000)),
                ('litrosCargados', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[aplicacion.models.validate_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioTurno', models.DateTimeField()),
                ('finTurno', models.DateTimeField()),
                ('bombaACargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bomba')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[aplicacion.models.validate_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('camioneta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.camioneta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargaCamioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCarga', models.DateTimeField(auto_now_add=True)),
                ('litrosCargados', models.PositiveIntegerField()),
                ('kilometrajeActual', models.PositiveIntegerField()),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bomba')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='CargaBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCarga', models.DateTimeField(auto_now_add=True)),
                ('litrosCargados', models.PositiveIntegerField()),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bomba')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bombero')),
            ],
        ),
    ]
