# Generated by Django 4.2.5 on 2023-12-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='rol',
        ),
        migrations.AlterField(
            model_name='bomba',
            name='capacidad',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='cargabomba',
            name='bomba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.bomba'),
        ),
        migrations.AlterField(
            model_name='cargabomba',
            name='bombero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.bombero'),
        ),
        migrations.AlterField(
            model_name='cargacamioneta',
            name='bomba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.bomba'),
        ),
        migrations.AlterField(
            model_name='cargacamioneta',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.chofer'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='camioneta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.camioneta'),
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
