# Generated by Django 4.2.4 on 2023-12-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_administrador_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomba',
            old_name='litrosCargados',
            new_name='litrosActuales',
        ),
    ]
